# Site Info

title: Dualog Hackathon 2018
hashtag: "#dualoghackathon"
url: https://github.com/dualog/

# Time for the countdown
time: "2018-06-21 09:30:00 +0200"

# Marketing
description: Prepare for the annual Dualog Hackathon this summer!

logo: logo.png

social-links:
  github: dualog
  twitter: Dualog_News
  instagram: dualog
  linkedin: dualog-as
  email: sales@dualog.com

# Developer stuff
link_color: 
social_link_color: black; 
background_color: "#f5f5f5"
download_button_text_color: white;
download_button_background_color: "#02405a"

version: v1.0
sass:
  style: :compressed

exclude:
  - README.md
  - LICENSE